/*
-- Usuarios
*/

INSERT INTO `ampabl`.`usuarios` (`idusuario`,`cargo`,`nombre`,`password`,`rol`,`username`) VALUES (1,'Tesorera','Patricia Jerez','$2a$10$iwMw1cC1GZ.lKZ8aDUq.e.x3/843Xt61hmLzTy9BDf4RD9CvftId.','ROLE_ADMIN','pjDatos');
INSERT INTO `ampabl`.`usuarios`  (`idusuario`,`cargo`,`nombre`,`password`,`rol`,`username`) VALUES (2,'Directora','Graciela Menéndez','$2a$10$/lgiQTNAV1i9UTxX4/DakedBRbqmXXuhuln1gS5xv5yKmmFIcy3Xa','ROLE_USER','Graci');
INSERT INTO `ampabl`.`usuarios`  (`idusuario`,`cargo`,`nombre`,`password`,`rol`,`username`) VALUES (3,'Administradora Sistema','Patricia','$2a$10$wdgiytE85nzblpkRZB/HxeSGG.mIpr5Ponu1FCQwkbrZmqjz5zGaq','ROLE_ADMIN','admin');
INSERT INTO `ampabl`.`usuarios`  (`idusuario`,`cargo`,`nombre`,`password`,`rol`,`username`) VALUES (4,'colaboradora','Lola','$2a$10$BxyOQbULi6UEgvJ3hzQq6emDk.F7sqOkPZixo1nN7BcSGXiDWSzXC','ROLE_USER','LolaMento');
INSERT INTO `ampabl`.`cursos` (`idcurso`, `nombrecurso`) VALUES ('1', '1º  E.S.O');
INSERT INTO `ampabl`.`cursos` (`idcurso`, `nombrecurso`) VALUES ('2', '2º  E.S.O');
INSERT INTO `ampabl`.`cursos` (`idcurso`, `nombrecurso`) VALUES ('3', '3º  E.S.O');
INSERT INTO `ampabl`.`cursos` (`idcurso`, `nombrecurso`) VALUES ('4', '4º  E.S.O');
INSERT INTO `ampabl`.`cursos` (`idcurso`, `nombrecurso`) VALUES ('5', '1º Bach_Ciencias');
INSERT INTO `ampabl`.`cursos` (`idcurso`, `nombrecurso`) VALUES ('6', '1º Bach_Humanidades');
INSERT INTO `ampabl`.`cursos` (`idcurso`, `nombrecurso`) VALUES ('7', '2º Bach_Ciencias');
INSERT INTO `ampabl`.`cursos` (`idcurso`, `nombrecurso`) VALUES ('8', '2º Bach_Humanidades');
INSERT INTO `ampabl`.`cursos` (`idcurso`, `nombrecurso`) VALUES ('9', '2º Bach_Bellas Artes');
INSERT INTO `ampabl`.`socios`  (`idsocio`,`nombrepadre`,`apellido1padre`,`apellido2padre`,`dnipadre`, `nombremadre`,`apellido1madre`,`apellido2madre`,`dnimadre`,`telefono`,`nombre`,`numhijos`,`alta`, `pagado`,`estado`) VALUES ('1', 'Jesús', 'García', 'Diegüez', '52617272B', 'Patricia','Jerez', 'Prado', '09434612N','667719132', 'García - Jerez', '2','2017','true', 'ALTA');
INSERT INTO `ampabl`.`alumnos` (`apellido1`, `apellido2`, `nombre`, `idcurso`, `idsocio`) VALUES ('García', 'Jerez', 'Celia', '9', '1');
INSERT INTO `ampabl`.`alumnos` (`apellido1`, `apellido2`, `nombre`, `idcurso`, `idsocio`) VALUES ('García', 'Jerez', 'Ana', '3', '1');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('1', 'Lengua Castellana y Literatura');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('2', 'Ingles');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('3', 'Francés');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('4', 'Matemáticas');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('5', 'Geografía e Historia');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('6', 'Geography & History');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('7', 'Biología y Geología');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('8', 'Biology & Geology');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('9', 'Educación Plástica');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('10', 'Música');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('11', 'Lengua Asturiana y Literatura');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('12', 'Mathematics');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('13', 'Física y Química');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('14', 'Tecnología');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('15', 'Cultura Clásica');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('16', 'Matemáticas Académicas');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('17', 'Matemáticas Aplicadas');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('18', 'Iniciación a la actividad emprendedora y empresarial');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('19', 'Cultura Científica');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('20', 'Tecnología de la Información y Comunicación');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('21', 'Historia');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('22', 'Latín');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('23', 'Economía');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('24', 'Ciencias Aplicadas a la Actividad Profesional');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('25', 'Dibujo Técnico');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('26', 'Tecnología Industrial');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('27', 'Anatomía Aplicada');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('28', 'Historia del mundo contemporáneo');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('29', 'Historia de España');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('30', 'Biología');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('31', 'Física');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('32', 'Química');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('33', 'Geografía');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('34', 'Griego');
INSERT INTO `ampabl`.`asignaturas`  (`idasignatura`, `nombreasignatura`) VALUES ('35', 'Historia del Arte');
/*LIBROS  1 ESO, pasado a la bbdd*/
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('1','Pulse 1','8', '67','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('2','Pulse 1 Workbook','8', '67','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('3', 'Parachute 1', '9','50','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('4', 'Parachute 1 cahier D´Exercices', '9','50','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('5', 'Matemáticas 1 Resuelve', '10','82','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('6', 'Geografía e Historia Descubre',  '51','42','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('7', 'Geography & History (2 volúmenes)', '1','23','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('8', 'Biología y Geología Aprender es crecer', '2','40','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('9', 'Biology & Geology Inicia dual', '3','25','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('10', 'Concierto 1', '5','35','EN_USO');
/*LIBROS  2 ESO,pasado a la bbdd*/
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('11', 'Pulse 2','52','35','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('12', 'Pulse 2 Workbook',  '52','36','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('13', 'Parachute 2',  '13','12','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('14', 'Parachute 2 cahier D´Exercices',  '13','12','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('15', 'Matemáticas 2 Resuelve',  '14','48','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('16', 'Mathematics 2',  '15','20','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('17', 'Geografía e Historia',  '16','67','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('18', 'Física y Química',  '17','29','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('19', 'Tecnología 2 Asturias, Inicia dual',  '18','42','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('20', 'Concierto 2',  '19','69','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('21', 'Cultura Clásica Evoca',  '20','15','EN_USO');
/*LIBROS  3 ESO,pasado a la bbdd*/
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('22', 'Pulse 3',  '22','65','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('23', 'Pulse 3 Workbook',  '22','61','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('24', 'Matemáticas Académicas Resuelve',  '28','22','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('25', 'Matemáticas Aplicadas Soluciona',  '29','26','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('26', 'Mathematics 3',  '30','15','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('27', 'Parachute 3',  '23','15','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('28', 'Parachute 3 cahier D´Exercices', '23','15','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('29', 'Física y Química, Investiga Proyecto saber', '31','63','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('30', 'Geografía e Historia 3',  '24','66','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('31', 'Biología y Geología Aprender es crecer', '25','55','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('32', 'Biology & Geology 3 Inicia dual',  '26','15','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('33', 'Cultura Clásica 3 Evoca',  '33','18','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('34', 'Iniciación a la actividad emprendedora 2',  '35','25','EN_USO');
/*LIBROS  4 ESO,pasado a la bbdd*/
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('35', 'Parachute 4', '38','14','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('36', 'Parachute 4 cahier D´Exercices', '38','2','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('37', 'Pulse 4', '37','61','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('38', 'Pulse 4 Workbook', '37','56','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('39', 'Cultura científica 4 SomosLink', '42','45','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('40', 'Matemáticas Académicas 4 Resuelve', '45','22','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('41', 'Matemáticas Aplicadas 4 Soluciona', '46','30','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('42', 'Historia 4 Teide', '47','63','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('43', 'Geography & History 4 (2 volúmenes)', '39','25','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('44', 'Biología y Geología 4 Dual (3 Volúmenes)', '40','35','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('45', 'Física y Química 4 Dual', '48','58','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('46', 'Música 4', '49','72','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('47', 'Latín 4 Interpreta', '50','17','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('48', 'Cultura Clásica 4 Evoca', '53','46','EN_USO');
/*1ºBach Ciencias*/
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('49', 'Trends 1', '54','32','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('50', 'Trends 1 Workbook','54','32','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('51', 'Biología y Geología 1º Dual','55','30','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('52', 'Física y Química 1º, Investiga Proyecto saber','57','26','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('53', 'Matemáticas 1º','56','46','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('54', 'Dibujo Técnico 1º','58','16','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('55', 'Tendances A2 Livre de L´Eleve','61','6','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('56', 'Anatomía aplicada 1º','62','46','EN_USO');
/*1ºBach Humanidades*/
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('57', 'Trends 1', '62','32','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('58', 'Trends 1 Workbook','62','32','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('59', 'Matemáticas Aplicadas a las Ciencias Sociales 1º','60','36','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('60', 'Economía 1º','50','19','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('61', 'Historia del mundo contemporáneo 1º','61','12','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('62', 'Latín 1º Interpreta','60','6','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('63', 'Tendances A2 Livre de L´Eleve','60','2','EN_USO');
/*2º Bach Ciencias*/
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('64', 'Trends 2','70','8','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('65', 'Trends 2 Workbook','70','5','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('66', 'Biología 2º','71','9','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('67', 'Física 2º, Investiga Proyecto saber', '72','6','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('68', 'Química 2º, Investiga Proyecto saber', '73','7','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('69', 'Dibujo Técnico 1º', '75','2','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('70', 'Tendances B1 Livre de L´Eleve','76','1','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('71', 'Matemáticas 2º','77','18','EN_USO');
/*2º Bach Humanidades*/
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('72', 'Geografía 2º','79','26','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('73', 'Trends 2','80','8','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('74', 'Trends 2 Workbook','80','5','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('75', 'Economía de la empresa','81','10','EN_USO');
INSERT INTO `ampabl`.`libros`  (`idlibro`,`titulo`, `idasignatura`,`numejemplares`,`estado`) VALUES ('76', 'Matemáticas Aplicadas a las Ciencias Sociales 2º', '82','11','EN_USO');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '1' WHERE (`idasignatura` = '1');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '1', `idlibro` = '1' WHERE (`idasignatura` = '2');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '1', `idlibro` = '3' WHERE (`idasignatura` = '3');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '1', `idlibro` = '5' WHERE (`idasignatura` = '4');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '1', `idlibro` = '6' WHERE (`idasignatura` = '5');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '1', `idlibro` = '7' WHERE (`idasignatura` = '6');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '1', `idlibro` = '8' WHERE (`idasignatura` = '7');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '1', `idlibro` = '9' WHERE (`idasignatura` = '8');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '1' WHERE (`idasignatura` = '9');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '1', `idlibro` = '10' WHERE (`idasignatura` = '10');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '1' WHERE (`idasignatura` = '11');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '2', `idlibro` = '16' WHERE (`idasignatura` = '12');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '2', `idlibro` = '18' WHERE (`idasignatura` = '13');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '2', `idlibro` = '19' WHERE (`idasignatura` = '14');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '2', `idlibro` = '21' WHERE (`idasignatura` = '15');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '3', `idlibro` = '24' WHERE (`idasignatura` = '16');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '3', `idlibro` = '25' WHERE (`idasignatura` = '17');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '3', `idlibro` = '34' WHERE (`idasignatura` = '18');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '3', `idlibro` = '33' WHERE (`idasignatura` = '19');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '3' WHERE (`idasignatura` = '20');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '3', `idlibro` = '42' WHERE (`idasignatura` = '21');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '4', `idlibro` = '47' WHERE (`idasignatura` = '22');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '4' WHERE (`idasignatura` = '23');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '4' WHERE (`idasignatura` = '24');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '4', `idlibro` = '54' WHERE (`idasignatura` = '25');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '4' WHERE (`idasignatura` = '26');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '4', `idlibro` = '56' WHERE (`idasignatura` = '27');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '5', `idlibro` = '61' WHERE (`idasignatura` = '28');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '5' WHERE (`idasignatura` = '29');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '5', `idlibro` = '66' WHERE (`idasignatura` = '30');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '5', `idlibro` = '67' WHERE (`idasignatura` = '31');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '5', `idlibro` = '68' WHERE (`idasignatura` = '32');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '6', `idlibro` = '72' WHERE (`idasignatura` = '33');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '6' WHERE (`idasignatura` = '34');
UPDATE `ampabl`.`asignaturas` SET `idcurso` = '9' WHERE (`idasignatura` = '35');
